### ISSUE TITLE
No such file or directory in createwallet cmd

### ISSUE THREAD

**Issue by bldgk** [KevinH2810/test-blockchain#1]
```
func (cli *CommandLine) createWallet(NodeId string) {
	wallets, _ := wallet.CreateWallet(NodeId)
	address := wallets.AddNewWallet()
	wallets.SaveFile(NodeId)

```

Write the instructions "How to start node, create wallet " in readme, please

**Comment by KevinH2810** [comment]
hello sir,

i have added the instruction to the readme. thank you for the comment.
sorry for any bugs that may occurs.
i'm open for any suggestions regarding the codes or the logics of how the
codes should behave.

best regards,
